### ISSUE TITLE
from django.db import models, migrations ImportError: cannot import name migrations

### ISSUE THREAD

**Issue by potar** [DjangoAdminHackers/django-linkcheck#37]
It seems to me you forgot to mention (https://github.com/DjangoAdminHackers/django-linkcheck/blob/master/CHANGELOG#L3) that the minimal software requirements are now Python 2.6 / Django 1.6 AND South 1.0 .  

The issue is: the package doesn't work with Django 1.6 and South versions that were released before 1.0 because the `migrations` was implemented later:
https://github.com/DjangoAdminHackers/django-linkcheck/blob/a2761f653add71ada4557a0f01dd413fc8737c59/linkcheck/migrations/0001_initial.py#L4
That's why the import error is occurred every time one tries to run a migration using older South version.
